# Generated by Django 3.2.7 on 2021-09-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verses',
            name='hizbQuarter',
            field=models.PositiveIntegerField(verbose_name='Hizb Quarter Number'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='juz',
            field=models.PositiveIntegerField(verbose_name='Juz Number'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='numberInQuran',
            field=models.PositiveIntegerField(verbose_name='Verse number in Quran'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='numberInSurah',
            field=models.PositiveIntegerField(verbose_name='Verse number in Surah'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='page',
            field=models.PositiveIntegerField(verbose_name='Page Number'),
        ),
    ]
