# Generated by Django 3.2.7 on 2021-09-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_verses_numberinquran'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verses',
            options={'ordering': ['verse_pk']},
        ),
        migrations.RenameField(
            model_name='verses',
            old_name='verseWithoutTaskeel',
            new_name='verseWithoutTashkeel',
        ),
    ]
