# Generated by Django 3.2.7 on 2021-11-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210922_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم السورة')),
                ('nameWithoutTashkeel', models.CharField(max_length=30, verbose_name='اسم السورة بدون تشكيل')),
            ],
        ),
        migrations.AlterField(
            model_name='verses',
            name='audio',
            field=models.URLField(unique=True, verbose_name='مصدر تلاوة أساسي'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='audio1',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='مصدر تلاوة ثانوي 1'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='audio2',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='مصدر تلاوة ثانوي 2'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='hizbQuarter',
            field=models.PositiveIntegerField(verbose_name='الربع'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='juz',
            field=models.PositiveIntegerField(verbose_name='الجزء'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='numberInQuran',
            field=models.PositiveIntegerField(unique=True, verbose_name='رقم الأية في القرءان'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='numberInSurah',
            field=models.PositiveIntegerField(verbose_name='رقم الأية في السورة'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='page',
            field=models.PositiveIntegerField(verbose_name='الصفحة'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='sajda',
            field=models.BooleanField(verbose_name='هل الأية تحتوي علي سجدة'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='verse',
            field=models.CharField(max_length=5000, verbose_name='الأية'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='verseWithoutTashkeel',
            field=models.CharField(max_length=1000, verbose_name='الأية بدون تشكيل'),
        ),
        migrations.AlterField(
            model_name='verses',
            name='verse_pk',
            field=models.CharField(max_length=8, unique=True, verbose_name='مفتاح الأية'),
        ),
    ]
