# Generated by Django 3.2.7 on 2021-11-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20211109_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surah',
            options={'verbose_name': 'سورة', 'verbose_name_plural': 'السور'},
        ),
        migrations.AlterModelOptions(
            name='verses',
            options={'ordering': ['verse_pk'], 'verbose_name': 'أية', 'verbose_name_plural': 'الأيات'},
        ),
        migrations.AddField(
            model_name='verses',
            name='surah',
            field=models.IntegerField(blank=True, null=True, verbose_name='السورة'),
        ),
    ]
