# Generated by Django 3.2.7 on 2021-11-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20211109_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surah',
            options={'ordering': ['id'], 'verbose_name': 'سورة', 'verbose_name_plural': 'السور'},
        ),
        migrations.AlterModelOptions(
            name='verses',
            options={'ordering': ['id'], 'verbose_name': 'أية', 'verbose_name_plural': 'الأيات'},
        ),
    ]
