# Generated by Django 3.2.7 on 2021-11-09 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20211109_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verses',
            name='surah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surah', to='search.surah', verbose_name='السورة'),
        ),
    ]
